extends: existence
message: "In general, don't use an ellipsis."
link: 'hhttps://nylas-style-guide.vercel.app/docs/language_and_grammar/punctuation/#ellipses'
nonword: true
level: warning
tokens:
  - '\.\.\.'