extends: existence
message: "Use first person (such as '%s') sparingly."
link: 'https://nylas-style-guide.vercel.app/docs/language_and_grammar/basics/#personal-pronouns'
ignorecase: true
level: warning
nonword: true
tokens:
  - (?:^|\s)I\s
  - (?:^|\s)I,\s
  - \bI'm\b
  - \bme\b
  - \bmy\b
  - \bmine\b