extends: existence
message: "Don't use foo, bar or foobar as data. Use actual data. '%s'"
link: 'https://nylas-style-guide.vercel.app/docs/formatting/code/'
nonword: true
level: error
tokens:
  - (?:(?:(?:foo))|(?:(?:bar))|(?:(?:foobar)))