extends: existence
message: "Spell out all ordinal numbers ('%s') in text."
link: 'https://nylas-style-guide.vercel.app/docs/formatting/numerals/#ordinal-numbers'
level: warning
nonword: true
tokens:
  - \d+(?:st|th|rd|nd|ly)