extends: existence
message: "Use the Oxford comma in '%s'."
link: 'https://nylas-style-guide.vercel.app/docs/language_and_grammar/punctuation/#comma'
scope: sentence
level: warning
tokens:
  - '(?:[^,]+,){1,}\s\w+\s(?:and|or)'