essage: "Write shorter sentences (less than 40 words)."
link: "https://nylas-style-guide.vercel.app/docs/writing-about-people/write-for-all/#write-clear-and-concise-text"
extends: occurrence
scope: sentence
level: suggestion
max: 40
token: \b(\w+)\b

# This catches an entire sentence and checks if its 40 character long.