name: Style Guide Check Vale
on: [pull_request]
jobs:
  reviewdog:
   name: reviewdog
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Vale
       uses: errata-ai/vale-action@v1.3.0
     - name: reviewdog
       uses: reviewdog/action-setup@v1
       with: 
         reviewdog_version: latest
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
