name: reviewdog
on: [pull_request]
jobs:
  # TODO: change `linter_name`.
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Changed Files
        id: get_changed_files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Vale
        uses: errata-ai/vale-action@v1.3.0
        with:
          files: '${{ steps.get_changed_files.outputs.all }}'
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: reviewdog/action-template@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: warning          
# name: Linting
# on: [push]

# jobs:
#   prose:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master
#     - name: Get Changed Files
#       id: get_changed_files
#       uses: lots0logs/gh-action-get-changed-files@2.1.4
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Vale
#       uses: errata-ai/vale-action@v1.3.0
#       with:
#         files: '${{ steps.get_changed_files.outputs.all }}'
#       env:
#         # Required
#         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
